### ISSUE TITLE
Room cleaning is not working anymore...

### ISSUE THREAD

**Issue by StefanoGiu** [And3rsL/Deebot-for-hassio#19]
2020-05-19 18:33:30 WARNING (SyncWorker_2) [deebotozmo.ecovacsiotmq] Event Not Found clean

**Comment by And3rsL** [comment]
it should work now

**Comment by StefanoGiu** [comment]
Still not working...

**Comment by And3rsL** [comment]
Did you update? It should be only a debug message and not a warning

**Comment by StefanoGiu** [comment]
Yes I updated... still not getting the room cleaning to work... I'm using the same scripts that before where working properly

**Comment by And3rsL** [comment]
Can you share your automation?

**Comment by StefanoGiu** [comment]
This was working before the upgrade of the component. Now the vacuum simply doesn't start...

I can still run a normal clean, but room cleaning is not working anymore:

`                          - entity: vacuum.aspirapolvere #cucina
                            icon: 'mdi:broom'
                            style:
                              left: 73%
                              top: 15%
                            tap_action:
                              action: call-service
                              service: vacuum.send_command
                              service_data:
                                command: spot_area
                                entity_id: vacuum.aspirapolvere
                                params:
                                  cleanings: 1
                                  rooms: 12
                            type: state-icon
`

**Comment by StefanoGiu** [comment]
Sorry, I just realized that my deebot has lost it's map.... again....

Does this happens to you also? Sometimes, it detecs changes in the environment and it starts drawing a new map, deleting the old one....

I've opened a ticket to Ecovacs, but they don't seem to listen...

**Comment by And3rsL** [comment]
Yes it happens to me sometimes when i move the robot manually, i found a workaround by save the map in the "multi floor" section

**Comment by StefanoGiu** [comment]
How can you save it?? Tell me, tell me :) :) :)

**Comment by StefanoGiu** [comment]
Let me explain the story:
- I started with multifloor
- It created the map and I split the room
- I used it for a while
- One day it said, environment changed, creating a new map
- I was able to restore it with a sequence of cleaning/return to dock...
- It happened again
- I disabled the multifloor and I created a new map
- After a while it happened again (yesterday)
- I cannot see the map saved anymore (from the map button of the app)
- I enabled back the multifloor, and the map appeared again
- I saved the map
- Still my deebot is not able to use that map...
- I tried with a sequence of clean/return to dock... but it doesn't restore the map, even if it's visible in the map section
- I tried to clean, turn off, move manually to dock, turn on... still not getting the map...

**Comment by StefanoGiu** [comment]
Is there a way I can force the deebot to use the saved map?

**Comment by StefanoGiu** [comment]
Btw, with a cycle of clean/return to dock I finally restored the map again... How do you do it?

Now, if I use the clean zone with your custom component, it doesn't seem to work. Room numbers are the same as before. 

What's wrong?

**Comment by StefanoGiu** [comment]
From the logs, I can read:

`2020-05-20 15:10:02 DEBUG (MainThread) [custom_components.deebot.vacuum] async_send_command spot_area ({'cleanings': '2', 'rooms': '12,0'}), {}
`

**Comment by StefanoGiu** [comment]
Hello, are you working on this issue? Please let me know, otherwise I will need to downgrade both HA and this component. Thanks a lot for your precious work so far.

**Comment by And3rsL** [comment]
Its working for me.. can you attach debug full log?

**Comment by StefanoGiu** [comment]
2020-05-20 15:10:02 DEBUG (MainThread) [custom_components.deebot.vacuum] async_send_command spot_area ({'cleanings': '2', 'rooms': '12,0'}), {}

This is what I get... after that... the vacuum doesn't start...

**Comment by And3rsL** [comment]
From ecovacs app work correctly? Rooms Number are correct?

**Comment by StefanoGiu** [comment]
Yes and yes :(

**Comment by StefanoGiu** [comment]
e.g.

`                          - entity: vacuum.aspirapolvere #sala
                            icon: 'mdi:broom'
                            style:
                              left: 66%
                              top: 45%
                              #--iron-icon-height: 30px
                              #--iron-icon-width: 30px              
                            tap_action:
                              action: call-service
                              service: vacuum.send_command
                              service_data:
                                command: spot_area
                                entity_id: vacuum.aspirapolvere
                                params:
                                  cleanings: 1
                                  rooms: 0
                            type: state-icon
`

My living room is "0". This code was working before. I don't get any error in the log and the vacuum doesn't start

![image](https://user-images.githubusercontent.com/35804888/82951806-29090300-9fa8-11ea-9bfc-e891467437c6.png)

**Comment by And3rsL** [comment]
se non sbaglio sei italiano! contattami su telegram che proviamo a capire il motivo @andr3rs
